# Generated by Django 2.2.1 on 2019-06-03 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190603_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sell',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='quantity',
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=30, null=True)),
                ('price', models.IntegerField()),
                ('fuel', models.CharField(max_length=30, null=True)),
                ('power', models.CharField(max_length=30, null=True)),
                ('prod', models.DateField()),
                ('mileage', models.IntegerField()),
                ('colour', models.CharField(max_length=30, null=True)),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car', to='main.Sell')),
            ],
        ),
    ]
