# Generated by Django 2.2.1 on 2019-06-03 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190603_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='car',
            name='mileage',
        ),
        migrations.RemoveField(
            model_name='car',
            name='power',
        ),
        migrations.RemoveField(
            model_name='car',
            name='title',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='user',
        ),
        migrations.AddField(
            model_name='car',
            name='sell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sell', to='main.Sell'),
        ),
    ]
