# Generated by Django 2.2.1 on 2019-06-03 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190604_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=30, null=True)),
                ('complete', models.BooleanField()),
                ('sell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Sell')),
            ],
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
