# Generated by Django 2.2.1 on 2019-06-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190604_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True)),
                ('category', models.CharField(max_length=30, null=True)),
                ('model', models.CharField(max_length=30, null=True)),
                ('marka', models.CharField(max_length=30, null=True)),
                ('price', models.IntegerField()),
                ('first_reg', models.DateField()),
                ('mileage', models.IntegerField()),
                ('fuel', models.CharField(max_length=20, null=True)),
                ('dsc', models.CharField(max_length=500, null=True)),
                ('img', models.ImageField(blank=True, upload_to='car_img')),
            ],
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Sell',
        ),
    ]
