# Generated by Django 2.2.1 on 2019-06-07 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190606_1607'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
