# Generated by Django 2.2.1 on 2019-06-07 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='checl',
            new_name='check',
        ),
    ]
