# Generated by Django 2.2.1 on 2019-06-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190607_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='check',
            field=models.BooleanField(null=True),
        ),
    ]
