# Generated by Django 2.2.1 on 2019-06-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190607_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='check',
            new_name='accident',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='offer',
            name='mm',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
