# Generated by Django 2.2.1 on 2019-07-02 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0016_offer_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='mm',
        ),
        migrations.AddField(
            model_name='offer',
            name='cap',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='category',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='colour',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='dsc',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='fuel',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='gear_box',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='marka',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='mileage',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='model',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='power',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='prod_year',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Userinf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_num', models.IntegerField(null=True)),
                ('adress', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userinf', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
