# Generated by Django 2.2.1 on 2019-07-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20190702_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='stan',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
