# Generated by Django 2.2.1 on 2019-07-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20190707_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='naped',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
