# Generated by Django 2.2.1 on 2019-07-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_offer_naped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='accident',
        ),
        migrations.AddField(
            model_name='offer',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
