# Generated by Django 2.2.1 on 2019-07-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20190707_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='stan',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
